### ISSUE TITLE
 Create a Two Lined Genome assembly with OTB

### ISSUE THREAD

**Issue by molikd** [molikd/otb#21]
In order to publish otb we need to run it on something, in this case the two lined spittle bug genome. 

target journal is g3

**Comment by molikd** [comment]
This is in progress, and currently running on Ceres

**Comment by Astahlke** [comment]
Will check this

**Comment by molikd** [comment]
This and the ag100 documentation issues are the last hurdles for starting to get ag100 people trained on otb

**Comment by molikd** [comment]
for reference this genome is in `/project/ag100pest/Prosapia_bivincta_otb_test/otb`

**Comment by molikd** [comment]
Currently re-running otb.
