### ISSUE TITLE
The hifi data input format only the bam format ？

### ISSUE THREAD

**Issue by zhangwenda0518** [molikd/otb#23]
Thank you for your work. I'm trying to use otb(only the best), but I see that the input of --readbam in wiki is bam file. I wonder if this can be in fasta format. Most assembly software uses fasta format files, and **I can't find my original bam file**. 

I tried to run it, but an error occurred. I don't know if I didn't understand it well. I hope you can give me some advice.

./otb.sh --runner none --mode homozygous --threads 40 -f 00.data/hic_R1.fastq -r 00.data/hic_R2.fastq --polish-type simple **--bam hifi.fatsa**

[Sun Jul  3 20:49:30 CST 2022]: checking runner
[Sun Jul  3 20:49:30 CST 2022]: none being used
[Sun Jul  3 20:49:30 CST 2022]: checking polishing
[Sun Jul  3 20:49:30 CST 2022]: simple/ragtag polishing
[Sun Jul  3 20:49:30 CST 2022]: building run parameters
[Sun Jul  3 20:49:30 CST 2022]: not running busco
[Sun Jul  3 20:49:30 CST 2022]: **reads file(s) not given, exiting**

thanks for your help！

**Comment by molikd** [comment]
This one is on me. 

the flag for the HiC data is is now:  -in or --reads I changed over from the "--bam" because I expanded the functionally from just bam files to include fastq

I'm going to keep this thread open for questions as you get setup.

**Comment by molikd** [comment]
closing due to no traffic.
