### ISSUE TITLE
trio mode needs parental reads, not hic

### ISSUE THREAD

**Issue by Astahlke** [molikd/otb#32]
Currently the trio mode of hifiam is using the HiC data, but it should be using maternal and paternal reads (https://hifiasm.readthedocs.io/en/latest/trio-assembly.html)
Need to set up optional parental reads channels. I think renaming the hic reads as such will also help clarify input and use cases.

**Comment by molikd** [comment]
Fair. theoretically we could keep the same channels, turning this into a clarity  problem

**Comment by molikd** [comment]
need to add right and left materinal and paternal

**Comment by molikd** [comment]
tested, fixed.
