### ISSUE TITLE
Build out bwa mem short read aligner container

### ISSUE THREAD

**Issue by Astahlke** [molikd/otb#34]
Need to build out bwa mem container https://github.com/lh3/bwa for #33

**Comment by molikd** [comment]
https://github.com/molikd/otb/commit/45b9d2352f373cf27242223eda03d47382950236 should fix this, needs testing before issue is closed.

**Comment by Astahlke** [comment]
Disagree! Minimap can handle short reads, but Hi-C are their own animal. Check out https://github.com/lh3/minimap2/issues/256 and https://lh3.github.io/2018/04/02/minimap2-and-the-future-of-bwa. The more recently updated readme of HiLine also recommends bwa-mem over minimap https://github.com/wtsi-hpag/HiLine

**Comment by molikd** [comment]
grr. I spent some time looking at weather we could use Nucmer or Unimap as well, just because I already have containers for those, no dice.

**Comment by molikd** [comment]
added bwa-mem2 for this in 713c771 all subsequent commands are switched over, and prefetch, checks are made as well.
