### ISSUE TITLE
Find a better small test dataset

### ISSUE THREAD

**Issue by Astahlke** [molikd/otb#39]
Soemthing from the hifasm git repo?

**Comment by molikd** [comment]
Semi relatedly, testing is currently taking place on 38fda7671731d702b66777090516c5c8f030eca0

**Comment by molikd** [comment]
should probably include Hi-C data as well. 

https://www.ncbi.nlm.nih.gov/sra?LinkName=biosample_sra&from_uid=20203776 <- small but I can't find hic

or maybe this one:

https://www.ncbi.nlm.nih.gov/assembly/GCA_002140095.1

**Comment by molikd** [comment]
The more I think about this lets just see if there is anything we have that is tiny and already published

**Comment by molikd** [comment]
Scott was saying that the indian meal moth (Pint) or Tribolium might be a good choice.

**Comment by molikd** [comment]
https://canu.readthedocs.io/en/latest/quick-start.html#quickstart
https://github.com/PacificBiosciences/DevNet/wiki/E.-coli-Bacterial-Assembly

**Comment by molikd** [comment]
I think we are going to need two e coli for HifiASM and then *something* with HiFi and HiC

**Comment by molikd** [comment]
see 

/project/ag100pest/otb_test 

on ceres

**Comment by molikd** [comment]
see:

SRR5413221 for HiC 
see SRR5413216 and SRR5413218 for HiFi 

currently in /project/ag100pest/otb_test/otb
