### ISSUE TITLE
Is ragtag a good default component?

### ISSUE THREAD

**Issue by Astahlke** [molikd/otb#40]
Ragtag could potentially generate false positives and incorrectly capture inversions between haplotypes. Inverted haplotype of chromosome 4 on locust genome could be a good case study.

**Comment by molikd** [comment]
We'll need to test this, 

HiC alignment to the haplotypes, then Juicebox, look at combined contig

need some genomes where we know there are inversions ONLY in on of the haplotypes

**Comment by molikd** [comment]
ragtag scaffold is now optional in "polishing" step as of 9248f5aeefcafecf16fbefdbca460fcdbe07d79f
