### ISSUE TITLE
generate the hic files 

### ISSUE THREAD

**Issue by molikd** [molikd/otb#52]
yahs juicer_pre for yahs outputs, and juicebox tools juicer pre for fragments list from hicstuff.

**Comment by Astahlke** [comment]
This is how we create .assembly and .hic for yahs
`# -a option creates an assembly that is editable in juicebox
juicer_pre -a -o no_ec no_ec.bin no_ec_scaffolds_final.agp genome.fasta.fai \
        2>tmp_juicer_pre_JBAT.log
grep "PRE_C_SIZE" tmp_juicer_pre_JBAT.log | cut -d' ' -f2- > no_ec_JBAT.chrom.sizes

java -jar -Xmx250G $JB_DIR/juicer_tools_1.22.01.jar pre \
        no_ec_scaffolds.txt no_ec_yahs.out.hic.part no_ec_yahs.JBAT.chrom.sizes  --threads 40
mv no_ec_yahs.out.hic.part no_ec_yahs.out.hic`

**Comment by molikd** [comment]
this requires a Java/Alpine container as base https://hub.docker.com/_/ibmjava 

Using 1.22

**Comment by molikd** [comment]
hicstuff does actually output a juicer ready level file, that's the agb file. The yahs output needs to be converted however, I added in the juicer_pre from hicstuff into the relevant yahs processes in 977018c

we will need the above container for a juicebox run to run juicer pre, basically we need something like:

`(java -jar -Xmx32G juicer_tools.1.9.9_jcuda.0.8.jar pre out_JBAT.txt out_JBAT.hic.part <(cat out_JBAT.log  | grep PRE_C_SIZE | awk '{print $2" "$3}')) && (mv out_JBAT.hic.part out_JBAT.hic)` 

This container will need java, and should probably have the xvfb hack we use for genomescope.

**Comment by Astahlke** [comment]
You don't need `xvfb` for the juicer_tools jar to produce the `hic` file.

**Comment by molikd** [comment]
I was thinking about putting it in so that it'd be a fully functional Juicer Singularity

**Comment by molikd** [comment]
this is in and works.
