### ISSUE TITLE
Pipeline not starting scaffolding steps due to missing --scaffold flag

### ISSUE THREAD

**Issue by dluecke** [molikd/otb#62]
When starting an OTB run via `otb.sh ... --yahs` the pipeline doesn't reach scaffolding associated steps (_eg_ `process yahs_faidx` and `process hicstuff`) because the value `params.scaffold = false` isn't modified.  `otb.sh` does not have a line to add the `--scaffold` flag to the `RUN="nextflow run run.nf "` string.  Adding `--scaffold ... -resume` to the `nextflow run` command and resubmitting to SLURM allows the run to reach scaffolding and further steps.  

An easy way to resolve this problem would be changing line 332 of `otb.sh` from
```[ -n "$YAHS" ] && RUN+="--yahs "```
to 
```[ -n "$YAHS" ] && RUN+="--scaffold --yahs "```

Thank you!

**Comment by molikd** [comment]
also be fixed in #64
