### ISSUE TITLE
yahs not finding inter-contig links due to missorted aln.bam file

### ISSUE THREAD

**Issue by dluecke** [molikd/otb#63]
The pre- and post-yahs assemblies are identical.  yahs runs fine but doesn't locate links between contigs because the bam file was sorted by position not read name, and yahs expects read pairs on subsequent lines.  Need to use `samtools sort -n` when generating aln.bam.

See this issue (https://github.com/c-zhou/yahs/issues/47) except in this case the read names are correct (pairs have correct/identical names) but aren't on adjacent lines so a similar error.

Can be fixed by adding the `-n` flag to the `samtools sort` command on lines 990, 1012, 1034, and 1056.  I made this change on line 990 for a no-polish run and got solid scaffolding.

**Comment by molikd** [comment]
this should be fixed in #64, closing.
